import React from 'react';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import { ShieldAlert, Clock, AlertTriangle, Send, Bell, RefreshCw } from 'lucide-react';

export const DealHealthDashboardView = ({ alerts = [], onEscalate, onNudge, onRecalculate }) => {
  const stalledCount = alerts.filter((a) => a.alert_type === 'Stalled Deal').length;
  const anomalyCount = alerts.filter((a) => a.alert_type === 'Discount Anomaly').length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Deal Health & Anomaly Engine</h1>
          <p className="text-sm text-slate-500">Autonomous detection of stalled quotes, margin slippages, and anomalies</p>
        </div>
        <Button variant="primary" icon={RefreshCw} onClick={onRecalculate}>
          Run Detection Recalculation
        </Button>
      </div>

      {/* Metric Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="border-rose-200 bg-rose-50/50">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-rose-700 uppercase tracking-wider">
              Stalled Deals (&gt;7 Days Idle)
            </span>
            <Clock className="w-5 h-5 text-rose-500" />
          </div>
          <div className="mt-4 flex items-baseline justify-between">
            <span className="text-3xl font-extrabold text-slate-900">{stalledCount}</span>
            <Badge variant="danger">Escalation Required</Badge>
          </div>
        </Card>

        <Card className="border-amber-200 bg-amber-50/50">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-amber-700 uppercase tracking-wider">
              Discount Anomalies
            </span>
            <AlertTriangle className="w-5 h-5 text-amber-500" />
          </div>
          <div className="mt-4 flex items-baseline justify-between">
            <span className="text-3xl font-extrabold text-slate-900">{anomalyCount}</span>
            <Badge variant="warning">Margin Slippage</Badge>
          </div>
        </Card>

        <Card className="border-purple-200 bg-purple-50/50">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#714B67] uppercase tracking-wider">
              Delivery Slippage Risk
            </span>
            <ShieldAlert className="w-5 h-5 text-[#714B67]" />
          </div>
          <div className="mt-4 flex items-baseline justify-between">
            <span className="text-3xl font-extrabold text-slate-900">0</span>
            <Badge variant="success">All Stock Reserved</Badge>
          </div>
        </Card>
      </div>

      {/* Flagged Anomaly Table */}
      <Card title="Flagged Deal Health Anomalies" subtitle="Real-time alerts generated by autonomous background detection engine">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-slate-700">
            <thead className="text-xs uppercase bg-slate-100 text-slate-500 border-b border-slate-200">
              <tr>
                <th className="py-3.5 px-4">Quote #</th>
                <th className="py-3.5 px-4">Customer Name</th>
                <th className="py-3.5 px-4">Alert Type</th>
                <th className="py-3.5 px-4">Anomaly Detail</th>
                <th className="py-3.5 px-4">Flagged Date</th>
                <th className="py-3.5 px-4">Status</th>
                <th className="py-3.5 px-4 text-right">Quick Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {alerts.map((al) => (
                <tr key={al.id} className="hover:bg-slate-50">
                  <td className="py-3.5 px-4 font-bold text-[#714B67]">{al.quote_number}</td>
                  <td className="py-3.5 px-4 font-medium text-slate-900">{al.customer_name}</td>
                  <td className="py-3.5 px-4">
                    <Badge variant={al.alert_type === 'Stalled Deal' ? 'danger' : 'warning'}>{al.alert_type}</Badge>
                  </td>
                  <td className="py-3.5 px-4 text-xs text-slate-600 max-w-xs">{al.detail}</td>
                  <td className="py-3.5 px-4 text-xs text-slate-500">{new Date(al.flagged_at).toLocaleDateString()}</td>
                  <td className="py-3.5 px-4">
                    <Badge variant={al.status === 'Escalated' ? 'danger' : al.status === 'Nudged' ? 'purple' : 'default'}>
                      {al.status}
                    </Badge>
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <Button size="sm" variant="warning" icon={Bell} onClick={() => onNudge(al.id)}>
                        Nudge Rep
                      </Button>
                      <Button size="sm" variant="danger" icon={Send} onClick={() => onEscalate(al.id)}>
                        Escalate
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};

export default DealHealthDashboardView;
